version: "3.9"

services:
  dev:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.base
    volumes:
      - ../..:/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PYTHONUNBUFFERED=1
    tty: true

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: monorepo_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
