FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/target/java-service-0.1.0.jar app.jar
EXPOSE 3005
CMD ["java", "-jar", "app.jar"]
